### ISSUE TITLE
how stallman accesses the internet

### ISSUE THREAD

**Issue by agraven** [arp242/arp242.net#19]
In his [how I do my computing](https://stallman.org/stallman-computing.html) page he additionally writes that he uses the icecat browser with tor to connect to sites he doesn't use regularly.

I am aware the footnote regarding the matter is a joke, but it may or may not be worth adding this detail for context. I know rms can be incredibly strange, but there's no need to present him as sillier than he is.

**Comment by Carpetsmoker** [comment]
Oh, looks like the IceCat stuff was added recently(ish). It's not in a 2015 archives copy anyway (I didn't re-read the entire document when I wrote it).

> the footnote regarding the matter is a joke

That's not exactly how I intended it; it's more of an interesting/funny aside, since RMS' method of browsing is pretty idiosyncratic. Note that with "funny" I don't mean "let's laugh *at* him", just amusing or interesting.

It's kind of a joke I guess, but not necessarily a "let's laugh at him" kind of joke. But I can see how it can be perceived like that.

I don't know ... I'll think about rephrasing or just removing it.

**Comment by arp242** [comment]
I removed this two weeks ago. I had planned to write a more extensive article about this (and did write a long draft), but my interests have since shifted to other things, and probably won't finish it any time soon.

The gist of it is that I feel that the programming community is already far too toxic, especially on the internet. This is something I've been annoyed about for quite some time, although, mea culpa, have also contributed to at times. If you're serious about wanting to change that you should go out of your way to be the exact opposite of that, even when you feel it's not really so bad.

There's more to it, but this is the short version and most important bit.

Thanks for reporting

**Comment by agraven** [comment]
I can certainly agree to the programming community being toxic, especially as someone belonging to a minority demographic.

I definitely understand your decision, sometimes your time is better spent than dealing with toxic internet people.
