### ISSUE TITLE
Use utterances for comments

### ISSUE THREAD

**Issue by zewa666** [arp242/arp242.net#21]
Hey there, I've stumbled across your site by reading an article mentioned in Javascript Weekly. I have to admit I like the minimalistic site Design but thought that topics like the one about jQuery could be more vivid including a comment section. Since you prefer GitHub issues as a feedback channel I wanted to make you aware of https://utteranc.es which essentially creates comments as issues in your repo. Take a look at my blog for a sample https://pragmatic-coder.net

Great articles, keep up the good work

**Comment by arp242** [comment]
Yeah, I'm familiar with it. Seems like a neat project.

Personally, I'm not so convinced of the value of directly adding comments. I like that it takes a bit of effort to send feedback (email or issue) rather than just typing in a box on the page. I have the feeling it encourages more quality replies.

I'm also not sure what the value is to the reader. If someone provides good feedback then I usually integrate it in the post, making the comment redundant. Other comments are just not useful to readers ("thanks, great post!"), or off-topic.

Sometimes people post rebuttals, which are sometimes reasonable (and sometimes not so reasonable), but I don't feel like I constantly need to engage in conversations about the validity of my posts on my own website. Do books post rebuttals by random people after it's finished? Would that improve the quality of the book? Probably not.

Also, there are usually Reddit/HN/Lobsters discussions too, which I link at the top for those who are interested.

**Comment by zewa666** [comment]
I tend to believe, or at least hope so, that good things can arise from discussion. Certainly trolls and fanboyism is a large scale issue in the industry but nevertheless its not all dark. Making it easy to enter a discussion through comments is a first step.

But I do get your reservation and its absolutely ok. Your site your rules ;)

**Comment by arp242** [comment]
It's not really my goal to host a discussion though; I primarily write my stuff for my own reasons. See: https://arp242.net/why-write.html

Feedback *is* often very useful, and usually take my time to respond with some amount of detail, but being receptive to feedback is not quite the same as hosting a discussion.

If you want to have a discussion then post to HN, Lobsters, Reddit, or some other place. I'll happily link to it.

**Comment by zewa666** [comment]
Again, I see your point. I guess we dont necessarily need to agree on the value of comments as this is not my intention. Frankly I just thought you preferred GitHub issues thats why i pointed out utterrances. But your explanation makes clear why you prefer to keep them out.
