### ISSUE TITLE
Linking broke down on https://www.arp242.net/git-hg.html

### ISSUE THREAD

**Issue by matkoniecz** [arp242/arp242.net#36]
https://www.arp242.net/git-hg.html 

> because it became a problem, [as Greg Kroah-Hartman explains][linus-fanboys]:

I am guessing that it is markdown and one of that likely should be in ( ) - probably second, but not sure

**Comment by arp242** [comment]
This seems to be caused by some customisations I made earlier today to offer plain text versions of all the posts; not entirely sure why it broke, but moving the references higher up seems to fix it 🤔 I'll have a more in-depth look when it's not 2am, but the live site should be good now.

Thanks for reporting the issue!

**Comment by matkoniecz** [comment]
BTW, it is a case of

> I feel I’m missing out on bug reports and patches because people simply can’t be bothered sending them on an unfamiliar platform.

If I would need more than 30 seconds to report (direct link to a place where I can report without logging in AND with a confirmation that reports are not ignored), then I would not bother with reporting it.

Sending me to

> Checking your browser before accessing gitlab.com.

shown at https://gitlab.com/users/sign_in for several seconds before allowing to attempt login would be enough to not report it (despite that I have an account there).
