### ISSUE TITLE
Vimlog

### ISSUE THREAD

**Issue by Konfekt** [arp242/arp242.net#47]
Good morning, and thank you very much for maintaining it, very useful to get up to speed every once in a while. Is it rather due to little activity on upstream or downstream that little seems to be happening recently?

**Comment by arp242** [comment]
> Is it rather due to little activity on upstream or downstream that little seems to be happening recently?

Just haven't had the time and interest to update it. It's a bit boring and tedious work; I need to look at the patches, and then understand the feature enough to make a concise one-line summary, which is harder than it sounds because there are some features I never use and am not all that familiar with.
